# See this for more options: https://github.com/not-matthias/apollo/blob/main/content/posts/configuration.md
# and this: https://github.com/not-matthias/apollo/blob/main/config.toml#L14

base_url = "https://bogdan.mocanu.ws"
title = "Bogdan"
description = "Personal site and blog of Bogdan Mocanu, software engineer and tech enthusiast"
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true

theme = "apollo"

taxonomies = [{ name = "tags" }]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = false

[markdown.highlighting]
# When set to "true", missing highlight languages are treated as errors. Defaults to false but recommended to set to true.
error_on_missing_language = true
# Selecting a theme is always required: you have a choice between single (1) or dual themes (2).
# Only outputting CSS classes like before 0.22 is not possible anymore.
# See here for themes: https://github.com/getzola/giallo?tab=readme-ov-file#themes
# 1. If you use a single theme, put its name here. See the syntax highlighting page for the possible choices.
theme = "ayu-dark"
# 2. If you want light/dark themes, use the 2 fields below instead. See the syntax highlighting page for the possible choices.
#light_theme = "ayu-light"
#dark_theme = "ayu-dark"
# Whether to use inline hex colours (`inline`) or CSS classes (`class`) 
#style = "inline"
# A list of files for additional JSON TextMate grammars
# See here for grammars: https://github.com/getzola/giallo?tab=readme-ov-file#grammars
# extra_grammars = []
# A list of files for additional JSON TextMate themes
# Get themes from https://textmate-grammars-themes.netlify.app/
# extra_themes = []


[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
logo = "site_logo.svg"
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/bmocanu/my-blog"

fediverse = false    # author attribution
fediverse_creator = ""    # e.g. @user@instance

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    { name = "/tags", url = "/tags", weight = 4 },
]

socials = [
    { name = "x/twitter", url = "https://x.com/bmocanu", icon = "x-twitter" },
    { name = "bluesky", url = "https://bsky.app/profile/bmocanu.bsky.social", icon = "bluesky" },
    { name = "linkedin", url = "www.linkedin.com/in/bmocanu", icon = "linkedin" },
    { name = "substack", url = "https://substack.com/@bmocanu", icon = "substack" },
    { name = "github", url = "https://github.com/bmocanu", icon = "github" },
]

stylesheets = [
    "custom.css"    # at /static/custom.css
]

[extra.taxonomies]
sort_by = "page_count"         # e.g. name, page_count
reverse = true

# [extra.analytics]
# enabled = false
# 
# [extra.analytics.goatcounter]
# user = "your_user"
# host = "example.com" # default= goatcounter.com
# 
# [extra.analytics.umami]
# website_id = "43929cd1-1e83...."
# host_url = "https://stats.mywebsite.com" # default: https://api-gateway.umami.dev/
# 
# [extra.analytics.google]
# tracking_id = "G-XXXXXXXXXX"  # Your Google Analytics tracking ID
